### ISSUE TITLE
Heroku import error

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/va-data-scraper#4]
When switching Postgres to Heroku we get the following error:  

```
[2017-12-20T20:09:33.582Z][ERROR] no pg_hba.conf entry for host "24.1.78....
```

**Comment by gondzo** [comment]
yup, heroku requires ssl for the database. Also, heroku has a limit for
total number of rows < 10k which is way too low for this. we either need a
paid postgress heroku instance or some other provider
